server:
  port: 9090

spring:
  application:
    name: Razorpay

  datasource:
    url: jdbc:mysql://localhost:3306/razorpayDB
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

payment:
  order:
    default-order-expiry-minutes: 30

  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    methods:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

vault:
  masterkey: kfhjhjhj55k4bjhgb334hkkjkdadsdagssdzxvcvzfsaawerewtghhh

jwt:
  secret-key: dsfhjlsdfheriuerjxhckj38lkzjhfdak0jlskjdlajdkjasqwe23jkhkjhkhj


